name: build && deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Current Repository
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.TOKEN }}

      - name: Use Node.js 12.x
        uses: actions/setup-node@v3
        with:
          node-version: '12.x'
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - run: npm install

      - name: build
        run: |
          rm -rf ./source/_posts && mkdir -p ./source/_posts
          cp -r leetcode/* ./source/_posts/
          npm run build

      - name: commit
        run: |
          git config --global user.email "beer5214@126.com"
          git config --global user.name "beer"
          
          git add public
          git commit -m 'auto build'
          git push
        


